spring:
  application:
    name: catalog-service
  config:
    import:
      "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:7070
      request-connect-timeout: 500
      request-read-timeout: 500
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1


server:
  port: 9090
  tomcat:
    threads:
      max: 50
      min-spare: 5
    keep-alive-timeout: 15s
    connection-timeout: 2s

polar:
  greeting: Hello World!!!
  enable-test-data: true