spring:
  application:
    name: catalog-service
  config:
    import:
      "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:7070
#      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    username: user
    password: password
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 9090
  tomcat:
    threads:
      max: 50
      min-spare: 5

polar:
  greeting: Hello World!!!
  enable-test-data: false

