name: Commit Stage

on:
  push:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'
          cache: 'gradle'
      - name: run buld and test
        run: |
          chmod +x gradlew
          ./gradlew build

