name: Commit Stage

on:
  push:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'
          cache: 'gradle'
      - name: Vulnerability Scanning
        uses: anchore/scan-action@v6
        with:
          path: ${{github.workspace}}
          fail-build: true
          severity-cutoff: critical
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
      - name: Upload Anchore SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{steps.scan.outputs.sarif}}
      - name: Build with unit and integration tests
        run: |
          chmod +x gradlew
          ./gradlew build 

